/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <Platforms_Types.h>

#define RCC_BASE 			0x40021000
#define GPIOA_BASE 			0x40010800

#define RCC_APB2ENR			*(vuint32_t *) (RCC_BASE + 0x18)
#define GPIOA_CRH 			*(vuint32_t *) (GPIOA_BASE + 0x04)
#define GPIOA_ODR 			*(vuint32_t *) (GPIOA_BASE + 0x0C)

typedef union{
	vuint32_t AllBits;
	struct{
		vuint32_t ReservedBits : 10;
		vuint32_t pin10 : 1;
	}pin;
}U_ODR_t;

volatile U_ODR_t *ODR = (volatile U_ODR_t*)(&GPIOA_ODR);

#define RCC_IOPAEN	(1<<2)

int main(void)
{
	RCC_APB2ENR |= RCC_IOPAEN;

	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;

	while(1){
		ODR->pin.pin10 = 1;
		for(int i = 0 ;i < 500 ; i++);

		ODR->pin.pin10 = 0;
		for(int i = 0 ;i < 500 ; i++);
	}
}
